### ISSUE TITLE
Production Bug

### ISSUE THREAD

**Issue by oguzhanaslan** [doabit/vue-ssr-starter-kit#11]
Hi. My local device is working in the development environment. 
I will run the application in a living environment. 

I'm running the 'npm run build' and `npm start` command on production server. 
Server:
`node:  v7.5.0`
`npm:  4.1.2`
`nginx reverse proxy server.js 8080 port`
`Ubuntu`

`npm run build` on server

browser devtool message:
> client-vendor-bundle.js:6 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': This node type does not support this method

**Comment by doabit** [comment]
@oguzhanaslan Which browser? I use chrome, it works.

**Comment by oguzhanaslan** [comment]
@doabit I use chrome. Tested it with other browsers. When, I run the `npm run build` command, get a warning message. Could it be related to this message?
Note: I am getting this error in production environment.
> WARNING in client-bundle.js from UglifyJs
Side effects in initialization of unused variable __WEBPACK_IMPORTED_MODULE_4_vuex_router_sync___default [client-bundle.js:407,25]
Side effects in initialization of unused variable state [client-bundle.js:519,5]
Side effects in initialization of unused variable state [client-bundle.js:530,5]
Side effects in initialization of unused variable __WEBPACK_IMPORTED_MODULE_0_vuex___default [client-bundle.js:740,25]
Side effects in initialization of unused variable __WEBPACK_IMPORTED_MODULE_0_vuex___default [client-bundle.js:808,25]
Side effects in initialization of unused variable _c [client-bundle.js:1347,78]
Condition always false [client-bundle.js:1545,3]
Dropping unreachable code [client-bundle.js:1547,1]
Side effects in initialization of unused variable update [client-bundle.js:1543,4]
Condition always false [client-bundle.js:1571,3]
Dropping unreachable code [client-bundle.js:1573,1]
Side effects in initialization of unused variable update [client-bundle.js:1569,4]
Condition always false [client-bundle.js:1597,3]
Dropping unreachable code [client-bundle.js:1599,1]
Side effects in initialization of unused variable update [client-bundle.js:1595,4]
Condition always false [client-bundle.js:1623,3]
Dropping unreachable code [client-bundle.js:1625,1]
Side effects in initialization of unused variable update [client-bundle.js:1621,4]
Condition always false [client-bundle.js:1649,3]
Dropping unreachable code [client-bundle.js:1651,1]
Side effects in initialization of unused variable update [client-bundle.js:1647,4]
Condition always false [client-bundle.js:1675,3]
Dropping unreachable code [client-bundle.js:1677,1]
Side effects in initialization of unused variable update [client-bundle.js:1673,4]
WARNING in client-vendor-bundle.js from UglifyJs
Condition always false [client-vendor-bundle.js:1262,10]
Dropping unreachable code [client-vendor-bundle.js:1263,8]
Condition left of && always false [client-vendor-bundle.js:1293,4]
Dropping side-effect-free statement [client-vendor-bundle.js:1293,4]
Condition left of && always false [client-vendor-bundle.js:1314,4]
Dropping side-effect-free statement [client-vendor-bundle.js:1314,4]
Condition always false [client-vendor-bundle.js:1559,17]
Dropping unreachable code [client-vendor-bundle.js:1560,8]
Condition always false [client-vendor-bundle.js:1599,6]
Dropping unreachable code [client-vendor-bundle.js:1600,4]
Condition always false [client-vendor-bundle.js:1660,6]
Dropping unreachable code [client-vendor-bundle.js:1661,4]
Condition always false [client-vendor-bundle.js:1698,6]
Dropping unreachable code [client-vendor-bundle.js:1699,4]
Condition left of && always false [client-vendor-bundle.js:1715,4]
Dropping side-effect-free statement [client-vendor-bundle.js:1715,4]
Condition always false [client-vendor-bundle.js:2064,8]
Dropping unreachable code [client-vendor-bundle.js:2065,6]
Condition left of && always false [client-vendor-bundle.js:2274,6]
Dropping side-effect-free statement [client-vendor-bundle.js:2274,6]
Condition left of && always false [client-vendor-bundle.js:2425,6]
Dropping side-effect-free statement [client-vendor-bundle.js:2425,6]
Condition left of && always false [client-vendor-bundle.js:2552,4]
Dropping side-effect-free statement [client-vendor-bundle.js:2552,4]
Condition always false [client-vendor-bundle.js:2683,12]
Dropping unreachable code [client-vendor-bundle.js:2684,10]
Condition always false [client-vendor-bundle.js:2693,10]
Dropping unreachable code [client-vendor-bundle.js:2694,8]
Boolean && always false [client-vendor-bundle.js:2816,10]
Condition always false [client-vendor-bundle.js:2816,10]
Dropping unreachable code [client-vendor-bundle.js:2817,8]
Condition left of && always false [client-vendor-bundle.js:2837,8]
Dropping side-effect-free statement [client-vendor-bundle.js:2837,8]
Condition always false [client-vendor-bundle.js:3051,10]
Dropping unreachable code [client-vendor-bundle.js:3053,8]
Condition always false [client-vendor-bundle.js:3138,10]
Dropping unreachable code [client-vendor-bundle.js:3139,8]
Condition always false [client-vendor-bundle.js:3147,10]
Dropping unreachable code [client-vendor-bundle.js:3148,8]
Condition always false [client-vendor-bundle.js:3239,6]
Dropping unreachable code [client-vendor-bundle.js:3240,4]
Condition always false [client-vendor-bundle.js:3270,8]
Dropping unreachable code [client-vendor-bundle.js:3272,6]
Condition always false [client-vendor-bundle.js:3601,8]
Dropping unreachable code [client-vendor-bundle.js:3602,6]
Condition left of && always false [client-vendor-bundle.js:3635,4]
Dropping side-effect-free statement [client-vendor-bundle.js:3635,4]
Condition left of && always false [client-vendor-bundle.js:3647,6]
Dropping side-effect-free statement [client-vendor-bundle.js:3647,6]
Condition always false [client-vendor-bundle.js:3670,8]
Dropping unreachable code [client-vendor-bundle.js:3671,6]
Condition always false [client-vendor-bundle.js:3713,8]
Dropping unreachable code [client-vendor-bundle.js:3714,6]
Condition always false [client-vendor-bundle.js:3756,6]
Dropping unreachable code [client-vendor-bundle.js:3757,4]
Condition always false [client-vendor-bundle.js:3828,8]
Dropping unreachable code [client-vendor-bundle.js:3829,6]
Condition always false [client-vendor-bundle.js:3886,6]
Dropping unreachable code [client-vendor-bundle.js:3887,4]
Condition always false [client-vendor-bundle.js:3950,8]
Dropping unreachable code [client-vendor-bundle.js:3951,6]
Condition always false [client-vendor-bundle.js:4009,12]
Dropping unreachable code [client-vendor-bundle.js:4010,10]
Condition always false [client-vendor-bundle.js:4137,6]
Dropping unreachable code [client-vendor-bundle.js:4138,4]
Condition left of && always false [client-vendor-bundle.js:4368,6]
Dropping side-effect-free statement [client-vendor-bundle.js:4368,6]
Dropping unused variable selector [client-vendor-bundle.js:4365,8]
Condition always false [client-vendor-bundle.js:4585,10]
Dropping unreachable code [client-vendor-bundle.js:4586,8]
Condition always false [client-vendor-bundle.js:4617,10]
Dropping unreachable code [client-vendor-bundle.js:4618,8]
Condition always false [client-vendor-bundle.js:4852,14]
Dropping unreachable code [client-vendor-bundle.js:4853,12]
Condition always false [client-vendor-bundle.js:4946,8]
Dropping unreachable code [client-vendor-bundle.js:4947,6]
Condition always false [client-vendor-bundle.js:4981,16]
Dropping unreachable code [client-vendor-bundle.js:4982,14]
Condition always false [client-vendor-bundle.js:5046,23]
Dropping unreachable code [client-vendor-bundle.js:5047,14]
Dropping unused function assertNodeMatch [client-vendor-bundle.js:5004,11]
Dropping unused variable inPre [client-vendor-bundle.js:4574,6]
Dropping unused variable bailed [client-vendor-bundle.js:4939,6]
Condition left of && always false [client-vendor-bundle.js:6151,4]
Dropping side-effect-free statement [client-vendor-bundle.js:6151,4]
Condition always false [client-vendor-bundle.js:977,4]
Dropping unreachable code [client-vendor-bundle.js:977,11]
Declarations in unreachable code! [client-vendor-bundle.js:978,2]
Declarations in unreachable code! [client-vendor-bundle.js:1001,2]
Condition always false [client-vendor-bundle.js:1356,4]
Dropping unreachable code [client-vendor-bundle.js:1357,2]
Condition left of && always false [client-vendor-bundle.js:1402,6]
Dropping side-effect-free statement [client-vendor-bundle.js:1402,6]
Condition always false [client-vendor-bundle.js:1891,4]
Dropping unreachable code [client-vendor-bundle.js:1891,11]
Declarations in unreachable code! [client-vendor-bundle.js:1892,2]
Declarations in unreachable code! [client-vendor-bundle.js:1913,4]
Declarations in unreachable code! [client-vendor-bundle.js:1927,2]
Condition always false [client-vendor-bundle.js:3367,21]
Condition left of && always false [client-vendor-bundle.js:3377,6]
Dropping side-effect-free statement [client-vendor-bundle.js:3377,6]
Condition left of && always false [client-vendor-bundle.js:3484,12]
Dropping side-effect-free statement [client-vendor-bundle.js:3484,12]
Condition always false [client-vendor-bundle.js:6097,8]
Dropping unreachable code [client-vendor-bundle.js:6098,6]
Condition always false [client-vendor-bundle.js:6367,8]
Dropping unreachable code [client-vendor-bundle.js:6368,6]
Condition always false [client-vendor-bundle.js:6378,8]
Dropping unreachable code [client-vendor-bundle.js:6379,6]
Condition always false [client-vendor-bundle.js:6490,19]
Dropping unreachable code [client-vendor-bundle.js:6490,26]
Declarations in unreachable code! [client-vendor-bundle.js:6491,10]
Dropping unused variable opts [client-vendor-bundle.js:6491,14]
Dropping unused variable name [client-vendor-bundle.js:6492,14]
Side effects in initialization of unused variable f [client-vendor-bundle.js:6545,8]
Condition always false [client-vendor-bundle.js:6638,4]
Dropping unreachable code [client-vendor-bundle.js:6639,2]
Condition always false [client-vendor-bundle.js:6653,6]
Dropping unreachable code [client-vendor-bundle.js:6655,6]
Dropping unused function checkComponents [client-vendor-bundle.js:1531,9]
Dropping unused function assertProp [client-vendor-bundle.js:1738,9]
Dropping unused function assertType [client-vendor-bundle.js:1791,9]
Dropping unused variable hasConsole [client-vendor-bundle.js:978,6]
Dropping unused variable formatLocation [client-vendor-bundle.js:1001,6]
Dropping unused variable initProxy [client-vendor-bundle.js:1889,4]
Dropping unused variable allowedGlobals [client-vendor-bundle.js:1892,6]
Dropping unused variable warnNonPresent [client-vendor-bundle.js:1899,6]
Dropping unused variable hasProxy [client-vendor-bundle.js:1908,6]
Dropping unused variable isBuiltInModifier [client-vendor-bundle.js:1913,8]
Dropping unused variable hasHandler [client-vendor-bundle.js:1927,6]
Dropping unused variable getHandler [client-vendor-bundle.js:1938,6]
Dropping unused variable circular [client-vendor-bundle.js:3228,4]
Dropping unused variable isReservedProp [client-vendor-bundle.js:3590,4]
Dropping unused variable modelableTagRE [client-vendor-bundle.js:6082,4]
Condition always true [client-vendor-bundle.js:6677,3]
Condition left of && always false [client-vendor-bundle.js:7577,6]
Dropping side-effect-free statement [client-vendor-bundle.js:7577,6]
Condition always false [client-vendor-bundle.js:8010,6]
Dropping unreachable code [client-vendor-bundle.js:8011,4]
Condition always false [client-vendor-bundle.js:8040,8]
Dropping unreachable code [client-vendor-bundle.js:8041,6]
Condition always false [client-vendor-bundle.js:8085,15]
Dropping unreachable code [client-vendor-bundle.js:8086,6]
Condition always false [client-vendor-bundle.js:8571,8]
Dropping unreachable code [client-vendor-bundle.js:8572,6]
Condition always false [client-vendor-bundle.js:8602,15]
Dropping unreachable code [client-vendor-bundle.js:8603,6]
Condition always false [client-vendor-bundle.js:8655,10]
Dropping unreachable code [client-vendor-bundle.js:8656,8]
Condition left of && always false [client-vendor-bundle.js:8704,6]
Dropping side-effect-free statement [client-vendor-bundle.js:8704,6]
Condition always false [client-vendor-bundle.js:8723,10]
Dropping unreachable code [client-vendor-bundle.js:8724,8]
Side effects in initialization of unused variable targetRecord [client-vendor-bundle.js:8722,10]
Condition always false [client-vendor-bundle.js:8849,6]
Dropping unreachable code [client-vendor-bundle.js:8850,4]
Condition always false [client-vendor-bundle.js:9575,10]
Dropping unreachable code [client-vendor-bundle.js:9576,8]
Condition left of && always false [client-vendor-bundle.js:9598,2]
Dropping side-effect-free statement [client-vendor-bundle.js:9598,2]
Dropping unused function assert [client-vendor-bundle.js:7453,9]
Condition left of && always true [client-vendor-bundle.js:9806,8]

**Comment by doabit** [comment]
I have updated node to 7.5.0, it still work on my mac, i haven't ubuntu device and didn't tested on it.
![6dc768d4-23ae-4cb9-9bc6-431b94a96887](https://cloud.githubusercontent.com/assets/330368/22593021/95aa728c-ea57-11e6-966b-749f8d8e3a08.png)

**Comment by oguzhanaslan** [comment]
I've updated Npm and Node versions. Now, I get a different error.
run: npm run build + npm start
Browser:

> client-vendor-bundle.js:7 
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
>     at Object.de [as appendChild] (http://example.com/dist/client-vendor-bundle.js:6:21456)

There is no problem on my local development env.

**Comment by doabit** [comment]
@oguzhanaslan Ubuntu 14.04 or 16.04

**Comment by oguzhanaslan** [comment]
i use 14.04 version.

**Comment by doabit** [comment]
I have tested on ubuntu 14.04, it still works.   -_-||
![10216103-faae-42c8-8cfa-d61a4669a407](https://cloud.githubusercontent.com/assets/330368/22679136/c829d370-ed3a-11e6-9728-99810feb45be.jpg)

**Comment by doabit** [comment]
Closed the issue, if you still have the problem,  i'll reopen it.

**Comment by Waakym** [comment]
Have the same Issues, OS x 10.11, node 7.7.3, I have this bug only on production

**Comment by doabit** [comment]
@Waakym Sorry, did you used the master branch?
