### ISSUE TITLE
Fresh install of `0.0.0` and I have  `Uncaught SyntaxError: Unexpected token <`

### ISSUE THREAD

**Issue by MachinisteWeb** [doabit/vue-ssr-starter-kit#13]
Hi,

I just discovered this kit and I test it yesterday and another time this day. I have always the same error.

I go to https://github.com/doabit/vue-ssr-starter-kit (here) 

I clone it with success (`git clone <url>`) .

I install the project (`npm install` ).

And I run it (`npm run dev`).

The website run on `http://localhost:3000/` and when I go to this url with Chrome

I have this two errors in client-side console

`Uncaught SyntaxError: Unexpected token <` from client-vendor-bundle.js:1

and

`Uncaught SyntaxError: Unexpected token <` from client-bundle.js:1

Why was wrong ?

![error](https://cloud.githubusercontent.com/assets/3882169/24070558/3daa343e-0bc0-11e7-93b1-904c397fa822.jpg)

**Comment by doabit** [comment]
@Haeresis I just tested it, it works.

```
❯ node -v
v7.1.0
```
```
❯ npm -v
3.10.9
```
![38532a54-3fd5-47a9-b9cb-b1ab3f3864b6](https://cloud.githubusercontent.com/assets/330368/24070773/932affa4-0bfe-11e7-81b6-ee727593c305.png)
![4f074df3-a18d-4132-816a-9636527b9bd4](https://cloud.githubusercontent.com/assets/330368/24070781/b6bcca42-0bfe-11e7-9a5a-30e898f64f98.png)

**Comment by MachinisteWeb** [comment]
I retry just at moment:

Node: v7.2.0
NPM: 3.10.9
OS: Windows 10

I also empty my cache. Others people with the same configuration and same problem?

**Comment by doabit** [comment]
I haven't window os, i tested on mac os 10.12.3, i'll try it again.

**Comment by MachinisteWeb** [comment]
I will first check if all user with Windows OS have this issue. If it is true. I will ask you to provide some test case to check where is the problem.

**Comment by doabit** [comment]
@Haeresis Sorry, I have found the reason, it caused by the last PR, https://github.com/doabit/vue-ssr-starter-kit/commit/0f6b37c0730d60bfb7d13b788a7f8224f97a9c5c#diff-abc8723150660069bca81f3f5515d6e9R24, i'll fix it.

**Comment by MachinisteWeb** [comment]
Ok! When it is done said to me and I will test it to assure you all is fine in order to close this issue.

**Comment by doabit** [comment]
@Haeresis  Updated, please to test it, thanks.

**Comment by MachinisteWeb** [comment]
@doabit  Ok for me, you can close.
