### ISSUE TITLE
State hydration on client

### ISSUE THREAD

**Issue by BorjaRafols** [doabit/vue-ssr-starter-kit#14]
Looks like SSR is working but data is being fetched again once on the client. The variable window.__INITIAL_STATE__ does not appear on the HTML generated by the server.

**Comment by doabit** [comment]
@BorjaRafols Sorry, i've no enough time to do that now, i'll take a look at it after some days.

**Comment by BorjaRafols** [comment]
@doabit That's good news, if I get it working before I'll submit a PR
