### ISSUE TITLE
 The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by Gala-1024** [doabit/vue-ssr-starter-kit#18]
**topics router reload err**

vue.runtime.esm.js:430 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

![wechatimg26](https://user-images.githubusercontent.com/2216048/27818364-f0d03a8e-60c7-11e7-9e1e-5b16ed347ecf.jpeg)

**Comment by doabit** [comment]
@cgygd Sorry for late reply, i think that because of vuejs have updated ssr implementation, i'll take a look.

**Comment by doabit** [comment]
@cgygd Fixed.
