### ISSUE TITLE
New instance for store

### ISSUE THREAD

**Issue by rainbowland302** [doabit/vue-ssr-starter-kit#22]
It seems the following returns the same instance.
`export default new Vuex.Store({
  state,
  actions,
  mutations,
  getters
})`
Should we return a new instance instance for SSR ?
`export function createStore () { ... }`

**Comment by doabit** [comment]
I think, the two methods do same work.

**Comment by joe223** [comment]
@doabit emmm, use factory function is required. Return the same instance will cause memory leak in some cases.
On the another hand，it will return chaotic Vuex data while server get different `request` from two users in same time if we store user info in same `VuexStore` instance.

Example: https://github.com/joe223/vue-ssr-memory-leak-example
  
BTW, I don't figure out yet (about `Vue.use()`) 😂

( I'll create a PR
