### ISSUE TITLE
replacing state with __INITIAL_STATE__ 2 times

### ISSUE THREAD

**Issue by MathieuDerelle** [doabit/vue-ssr-starter-kit#23]
shouldn't this disappear ?
https://github.com/doabit/vue-ssr-starter-kit/blob/2b036e8a87a5e1b546e0284e20d1031e88a8d04f/src/vuex/store.js#L16

since it is done there 
https://github.com/doabit/vue-ssr-starter-kit/blob/2b036e8a87a5e1b546e0284e20d1031e88a8d04f/src/client-entry.js#L6

**Comment by doabit** [comment]
@MathieuDerelle Thanks, fixed.
