### ISSUE TITLE
Rendering static assets that work without the server

### ISSUE THREAD

**Issue by janwirth** [doabit/vue-ssr-starter-kit#25]
First off - awesome tool. Thank you

So I developed my entire site in with this tool and now I want to deploy my static, server-side-rendered assets to the UI for quick rendering but added interactivity through hydration. Now I figured that `vue-ssr-starter-kit` actually requires running a server.

I managed to get the artifacts I need by saving the site served by `npm start`, but this is not an optimal process.

Is there an intention to make this use case more efficient? How would you implement that? All I need is the site as server by the prod server.

Regards

**Comment by doabit** [comment]
@FranzSkuffka Sorry, the project is only a starter kit for vue ssr, you can implement that  if you need other features.
