### ISSUE TITLE
HTML not render with build

### ISSUE THREAD

**Issue by vishalmindinventory** [doabit/vue-ssr-starter-kit#29]
Hello,
I had created build without error, but issue with render HTML. I don't know what is an issue with build. But same thing work when I try to run with "npm run dev".

I am using below versions
Node - v10.6.0
NPM - v6.1.0
Ubuntu - 18.04
![screenshot from 2018-07-18 12-13-37](https://user-images.githubusercontent.com/18322365/42864440-129e0f9c-8a84-11e8-9cbd-228518fbd9f8.png)

**Comment by doabit** [comment]
What  error?

**Comment by vishalmindinventory** [comment]
Sorry for the late reply.
I solved an issue. Style loader creates an issue with product mode.
