### ISSUE TITLE
Can't resolve 'babel' 

### ISSUE THREAD

**Issue by Abonive** [doabit/vue-ssr-starter-kit#4]
I just cloned the master branch and ran the "npm install" but when running the "npm run build" i get an error. 

> ERROR in Entry module not found: Error: Can't resolve 'babel' in 'PathToProject/vue-ssr-starter-kit'

I haven't change anything so its weird that it doesnt work.

**Comment by Abonive** [comment]
It's was because of the update in Webpack 2.1.0-beta26. I've created a fork and fixed the issue.

**Comment by doabit** [comment]
@Abonive Could you give a pr? thanks.
