### ISSUE TITLE
请问怎样分离css 

### ISSUE THREAD

**Issue by JulyYangOne** [doabit/vue-ssr-starter-kit#47]
请问怎样分离css

**Comment by doabit** [comment]
这个已经很久的了，现在如果对ssr有需求，推荐使用nuxtjs或者参考最新的文档 https://ssr.vuejs.org/zh/guide/css.html#%E5%90%AF%E7%94%A8-css-%E6%8F%90%E5%8F%96

**Comment by JulyYangOne** [comment]
按照文档写了 还是出不来 关闭注入的话  js也一起关闭了

**Comment by JulyYangOne** [comment]
可否加个联系方式  请教一下怎么做

**Comment by doabit** [comment]
> 可否加个联系方式 请教一下怎么做

wx:    d3hpZF9wenhseTkyNWlkMnYyMQ==

**Comment by JulyYangOne** [comment]
用户不存在  麻烦加我 197653770

**Comment by doabit** [comment]
Fixed https://github.com/doabit/vue-ssr-starter-kit/pull/51
